### Local connection
POST http://127.0.0.1:8980/push
Content-Type: application/json

{
  "target": "arn:aws:sns:000000000000:we-are-in-live",
  "message": "{\"default\": \"we are in live\"}",
  "subject": "SOME_EVENT"
}
###
### Topic
POST http://27.0.0.1:8980/topic
Content-Type: application/json

{
  "topic": ":000000000000:we-are-in-live",
  "message": "FACE_DETECTED",
  "subject": "FACE_DETECTED"
}
###